language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: nightly
sudo: false
install: pip3 install sqlalchemy praw configparser
script: tests.py